[package]
name = "mini_rag"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ort = "=2.0.0-rc.10"
serde = "1.0.219"
serde_json = "1.0.140"
text-splitter = "0.27.0"
tokenizers = "0.21.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }